// Copyright 2026 RRRTX Labs
// Use of this source code is governed by the MPL-2.0 license that can be
// found in the LICENSE file.
//
// P15 T4 — permission-audit-event-v1 and the frozen ActivityRow.
//  * GOLDEN: every line of docs/contracts/tests/golden-permission-audit-event
//    .jsonl (written by an independent Python canonicalizer) is parsed, rebuilt
//    into an AuditRow, regenerated by the C++ generator, and must match its
//    line byte-for-byte. Two implementations, one set of bytes.
//  * REDACTION: a full origin (scheme, path, query, port, userinfo, uppercase)
//    is refused, never truncated into a registrable domain.
//  * SHAPE: an audit row has exactly the twelve documented keys, so a planted
//    usage field cannot ride along.
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "permissions/core/audit.h"
#include "permissions/core/json.h"
#include "policy/tests/harness.h"

using namespace xr::permissions;

namespace {

std::string GoldenPath() {
  const char* env = std::getenv("XR_BROWSER_ROOT");
  std::string root = (env != nullptr && *env) ? env : "../../../xr-browser";
  return root + "/docs/contracts/tests/golden-permission-audit-event.jsonl";
}

bool ParseEventName(const std::string& s, AuditEvent* out) {
  if (s == "grant") { *out = AuditEvent::kGrant; return true; }
  if (s == "revoke") { *out = AuditEvent::kRevoke; return true; }
  if (s == "expiry") { *out = AuditEvent::kExpiry; return true; }
  return false;
}

bool ParseLayerName(const std::string& s, DecidingLayer* out) {
  if (s == "identity_overlay") { *out = DecidingLayer::kIdentityOverlay; return true; }
  if (s == "global_fallback") { *out = DecidingLayer::kGlobalFallback; return true; }
  return false;
}

// Rebuilds the row from its JSON fields (the reverse of AuditRowJson).
bool RowFromJson(const JsonValue& o, AuditRow* r) {
  auto str = [&](const char* k, std::string* out) {
    const JsonValue* f = o.find(k);
    if (f == nullptr || !f->is_string()) return false;
    *out = f->as_string();
    return true;
  };
  auto num = [&](const char* k, int64_t* out) {
    const JsonValue* f = o.find(k);
    if (f == nullptr || !f->is_int()) return false;
    *out = f->as_int();
    return true;
  };
  std::string ev, cap, layer;
  if (!str("event", &ev) || !ParseEventName(ev, &r->event)) return false;
  if (!str("identity", &r->identity) || !str("capability", &cap) || !ParseCapability(cap, &r->capability)) return false;
  if (!str("origin", &r->origin) || !str("scope", &r->scope) || !str("reason", &r->reason)) return false;
  if (!str("deciding_layer", &layer) || !ParseLayerName(layer, &r->deciding_layer)) return false;
  return num("ts_millis", &r->ts_millis) && num("ttl_millis", &r->ttl_millis);
}

}  // namespace

int main() {
  // --- GOLDEN: byte-for-byte across two implementations ----------------------
  {
    std::ifstream in(GoldenPath());
    XR_EXPECT_MSG(in.good(), "golden audit fixture readable (XR_BROWSER_ROOT set?)");
    std::string line;
    int rows = 0, matched = 0;
    bool saw[3] = {false, false, false};
    while (std::getline(in, line)) {
      if (line.empty()) continue;
      ++rows;
      auto pr = ParseJson(line);
      AuditRow r;
      if (!pr.ok || !RowFromJson(pr.value, &r)) {
        XR_EXPECT_MSG(false, "golden line parses into an audit row: " + line.substr(0, 60));
        continue;
      }
      saw[static_cast<int>(r.event)] = true;
      std::string regenerated = AuditRowJson(r);
      if (regenerated == line) ++matched;
      XR_EXPECT_MSG(regenerated == line, "generator bytes == golden bytes: " + line.substr(0, 80));
    }
    XR_EXPECT_MSG(rows >= 9, "golden covers the event classes");
    XR_EXPECT_MSG(matched == rows, "every golden row regenerates byte-for-byte");
    XR_EXPECT_MSG(saw[0] && saw[1] && saw[2], "golden covers grant, revoke and expiry");
  }

  // --- REDACTION: only a bare registrable domain survives --------------------
  {
    std::string out;
    XR_EXPECT_MSG(RedactOrigin("example.com", &out) && out == "example.com", "bare domain accepted");
    XR_EXPECT_MSG(RedactOrigin("a-b.example.co.uk", &out), "multi-label accepted");
    XR_EXPECT_MSG(!RedactOrigin("https://example.com", &out), "scheme refused");
    XR_EXPECT_MSG(!RedactOrigin("example.com/private/path", &out), "path refused");
    XR_EXPECT_MSG(!RedactOrigin("example.com?token=abc", &out), "query refused");
    XR_EXPECT_MSG(!RedactOrigin("example.com#frag", &out), "fragment refused");
    XR_EXPECT_MSG(!RedactOrigin("example.com:8443", &out), "port refused");
    XR_EXPECT_MSG(!RedactOrigin("user@example.com", &out), "userinfo refused");
    XR_EXPECT_MSG(!RedactOrigin("Example.com", &out), "uppercase refused");
    XR_EXPECT_MSG(!RedactOrigin("", &out), "empty refused");
    XR_EXPECT_MSG(!RedactOrigin(".example.com", &out), "leading dot refused");
    XR_EXPECT_MSG(!RedactOrigin("example..com", &out), "doubled dot refused");
    XR_EXPECT_MSG(!RedactOrigin("-example.com", &out), "leading hyphen refused");
    XR_EXPECT_MSG(!RedactOrigin("exa mple.com", &out), "space refused");
    XR_EXPECT_MSG(!RedactOrigin(std::string(254, 'a'), &out), "over-length refused");
  }

  // --- SHAPE: exactly the documented keys, nothing else -----------------------
  {
    AuditRow r;
    r.identity = "xr:00000000-0000-4000-8000-0000000000a1";
    r.origin = "example.com";
    r.scope = "once";
    r.reason = "user-grant";
    auto pr = ParseJson(AuditRowJson(r));
    XR_EXPECT_MSG(pr.ok && pr.value.is_object(), "audit row is a JSON object");
    XR_EXPECT_MSG(pr.value.as_object().size() == 12, "exactly twelve keys (no usage or extra fields)");
    XR_EXPECT_MSG(pr.value.find("usage_active") == nullptr, "no usage field exists");
    XR_EXPECT_MSG(pr.value.find("determinism_note") != nullptr, "determinism note present");
  }

  // --- ActivityRow: frozen shape, kind = kPermission, human summary ----------
  {
    AuditRow r;
    r.identity = "xr:00000000-0000-4000-8000-0000000000a1";
    r.origin = "example.com";
    r.event = AuditEvent::kGrant;
    r.capability = Capability::kCamera;
    r.scope = "once";
    r.ts_millis = 42;
    auto pr = ParseJson(ActivityRowJson(r));
    XR_EXPECT_MSG(pr.ok && pr.value.as_object().size() == 4, "activity row has the four frozen fields");
    XR_EXPECT_MSG(pr.value.find("kind") != nullptr && pr.value.find("kind")->as_string() == "kPermission",
                  "kind is kPermission");
    XR_EXPECT_MSG(pr.value.find("summary") != nullptr && pr.value.find("summary")->as_string() ==
                      "Allowed camera for example.com (once)",
                  "summary is a human sentence, not a code");
    AuditRow all;
    all.event = AuditEvent::kRevoke;
    all.capability = Capability::kMicrophone;
    all.reason = "revoke_all";
    XR_EXPECT_MSG(ActivitySummary(all) == "Revoked microphone for all sites (revoke_all)",
                  "identity-wide rows say 'all sites'");
  }

  return xrtest::Report("test_audit");
}
